{
 "title": "Home",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of processed blocks / 2min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(processed_blocks_counter[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (100 * (node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of processed blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "processed_blocks_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of processed rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "processed_rollbacks_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {}
   ]
  }
 ]
}