#!/usr/bin/env bash

set -euo pipefail

PORT=3000

banner() {
  echo '============================================='
  echo '==' "${@}"
  echo '============================================='
  echo ''
}

get() {
  local ENDPOINT=$1
  local FORMAT=${2-cat}

  echo -n "GET /$ENDPOINT -> "
  curl -sS --fail-with-body "http://localhost:$PORT/$ENDPOINT" | "$FORMAT"
  echo ''
}

query() {
  local method=$1
  local params=$2

  echo "$method($(jq -C . <<<"$params")) ="
  curl -sS --fail-with-body \
    -H 'Content-Type: application/json' \
    -d '{"jsonrpc": "2.0", "method": "'"$method"'", "params": '"$params"', "id": 1}' \
    "http://localhost:$PORT/json-rpc" \
    | jq
  echo ''
}

banner "REST APIs"

get time
get params jq
get addresses jq
get metrics

banner "unknownMethod"

query "unknownMethod" '""'

banner "echo"

query "echo" '"Hello, World!"'

banner "getTargetAddresses"

query "getTargetAddresses" '""'

banner "getCurrentSyncedBlock"

query "getCurrentSyncedBlock" '""'

banner "getUtxosFromAddress"

# The cardano-db-sync query to get addresses with the most utxos:
# select address, count(*) as c from tx_out, tx, block where tx_out.tx_id = tx.id and tx.block_id = block.id group by address order by c desc limit 1;

query "getUtxosFromAddress" '{"address": "addr_test1vz09v9yfxguvlp0zsnrpa3tdtm7el8xufp3m5lsm7qxzclgmzkket", "unspentBeforeSlotNo": 30000000}'
query "getUtxosFromAddress" '{"address": "addr_test1vz09v9yfxguvlp0zsnrpa3tdtm7el8xufp3m5lsm7qxzclgmzkket", "createdAtOrAfterSlotNo": 16052985, "unspentBeforeSlotNo": 18364224}'

banner "getBurnTokenEvents"

# The cardano-db-sync query to get burn events:
# select multi_asset.policy, multi_asset.name, block.slot_no, tx.hash from tx, ma_tx_mint, multi_asset, redeemer, block where tx.id = ma_tx_mint.tx_id and multi_asset.id = ma_tx_mint.ident and redeemer.tx_id = tx.id and tx.block_id = block.id limit 1;

query "getBurnTokenEvents" '{"policyId": "e2bab64ca481afc5a695b7db22fd0a7df4bf930158dfa652fb337999", "assetName": "53554d4d495441574152445344656669", "createdBeforeSlotNo": 11639233}'
query "getBurnTokenEvents" '{"policyId": "e222ae950cef1915dcb9db8840dc9c3df3785f9a10eca30dfb84ad40"}'
query "getBurnTokenEvents" '{"policyId": "e222ae950cef1915dcb9db8840dc9c3df3785f9a10eca30dfb84ad40", "createdBeforeSlotNo": 10944386}'
query "getBurnTokenEvents" '{"policyId": "e222ae950cef1915dcb9db8840dc9c3df3785f9a10eca30dfb84ad40", "afterTx": "0a872c4fcf87f041caab5d5ecaeae19fd0e26de14241167c8dee7d1b26b5b4f7"}'

banner "getNonceByEpoch"

query "getNonceByEpoch" '3'
query "getNonceByEpoch" '4'

banner "getActiveStakePoolDelegationByEpoch"

query "getActiveStakePoolDelegationByEpoch" '7'
query "getActiveStakePoolDelegationByEpoch" '31'
