---
steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true
  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: false

  - trailing_whitespace: {}
columns: 120
newline: native
<<<<<<< HEAD:.stylish-haskell.yaml
language_extensions: [FlexibleContexts, DerivingStrategies, GeneralizedNewtypeDeriving]
=======
language_extensions: [FlexibleContexts, DeriveGeneric, DeriveAnyClass, DerivingStrategies, GeneralizedNewtypeDeriving]
>>>>>>> 3e0bd6917753c5373678c92796bed5257eeaa7f6:language-plutus-core/.stylish-haskell.yaml
