= https://github.com/input-output-hk/marconi[Cardano Blockchain Indexer Framework]
:email: plutus@iohk.io
:author: Input Output HK Limited
:toc: left
:reproducible:

image:https://img.shields.io/badge/policy-Cardano%20Engineering%20Handbook-informational[link=https://input-output-hk.github.io/cardano-engineering-handbook]

== Introduction

Marconi is a lightweight customizable solution for indexing and querying the Cardano blockchain.

== Key features

To be completed...

A comparison with other chain-indexing projects is also https://example.com/TODO[available].

== Quick start

To be completed...

== Documentation

=== User documentation

The more in-depth user documentation is available in our http://example.com/TODO[website].

=== Haddock documentation

The Haskell API documentation (Haddock) for the Marconi libraries is hosted here:
* https://input-output-hk.github.io/marconi/main/marconi-core[marconi-core]
* https://input-output-hk.github.io/marconi/main/marconi-chain-index[marconi-chain-index]
* https://input-output-hk.github.io/marconi/main/marconi-core-json-rpc[marconi-core-json-rpc]

You may generate them directly with `Cabal` for each component:

```
cabal haddock marconi-core
cabal haddock marconi-core-json-rpc
cabal haddock marconi-chain-index
```

[[Architecture]]
== Architecture overview

See the http://example.com/TODO[Design and Architecture] section the website for more in-depth explainations.

== CONTRIBUTING

[[how-to-develop]]
=== How to contribute code (or documentation) to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING] for comprehensive documentation on how to contribute to the project, including development, and how to submit changes.

=== How to submit an issue

Issues can be filed in the https://github.com/input-output-hk/marconi/issues[GitHub Issue tracker].

== Roadmap

To be completed...

== Licensing

You are free to copy, modify, and distribute the Marconi project with under the terms of the Apache 2.0 license.
See the link:./LICENSE[LICENSE] and link:./NOTICE[NOTICE] files for details.
