= HTTP API
:toc: left
:toclevels: 2

This document describes the HTTP API that end-users interact with in order to query the data indexed by `marconi-sidechain`.

== HTTP endpoints

In this application, the following HTTP endpoints/routes are available:

[%header%autowidth,format=csv]
|===
Route,Methods,ContentType
`/json-rpc`,`POST`,JSON
`/addresses`,`GET`,Text
`/metrics`,`GET`,Text
`/params`,`GET`,JSON
`/time`,`GET`,Text
|===

The `/json-rpc` endpoint responds to well-formed link:https://www.jsonrpc.org/specification[JSON-RPC version 2] requests.
The JSON-RPC methods that can be used are described <<_supported_json_rpc_methods,below>>.

The `/addresses` endpoint returns the list of target addresses represented as Bech32 text in a JSON string array.

The `/metrics` endpoint returns Prometheus metrics for monitoring the runtime behavior.

The `/params` endpoint returns the parsed command-line parameters as a JSON object.

The `/time` endpoint returns the current time as text. It's typically used for testing the http server outside of JSON-RPC.

== JSON-RPC HTTP endpoint request and response format

As defined by the JSON-RPC specification, `marconi-sidechain` can process the following JSON-RPC HTTP request and response format.

[NOTE]
====
All JSON formats in this document are described using link:https://json-schema.org[JSON-Schema].
====

.JSON-RPC HTTP request body
[%collapsible]
====
```JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "jsonrpc": {
      "type": "string"
    },
    "method": {
      "type": "string"
    },
    "params": {
      "type": {}
    },
    "id": {
      "type": "integer"
    }
  },
  "required": [
    "jsonrpc",
    "method",
    "params",
    "id"
  ]
}
```
====

.JSON-RPC HTTP response body
[%collapsible]
====
```JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "jsonrpc": {
          "type": "string"
        },
        "result": {}
      },
      "required": [
        "id",
        "jsonrpc",
        "result"
      ]
    },
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "jsonrpc": {
          "type": "string"
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "number"
            },
            "message": {
              "type": "string"
            },
            "data": {}
          },
          "required": [
            "code",
            "message"
          ]
        }
      },
      "required": [
        "id",
        "jsonrpc",
        "error"
      ]
    }
  ]
}
```
====

== Error object

In case of runtime errors, the JSON-RPC server will respond with any of the predefined errors code defined here: https://www.jsonrpc.org/specification#error_object.
However, each supported JSON-RPC methods described below will respond with a custom `data` field which provides additional/detailed information about the error.

== Supported JSON-RPC methods

=== echo

Echoes a message back as a JSON-RPC response.

==== Pre-conditions

None. Any string may be given as input.

==== Post-conditions

The result is the same as the input parameter.

==== Rationale

Used for testing the server.

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "string",
  "description": "Message to be echoed",
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "string",
  "description": "Echoed input message",
}
```
====

[NOTE]
====
This method does not return errors.
====

=== getTargetAddresses

Returns the list of target addresses represented as Bech32 text, as an array of strings.

==== Pre-conditions

None as the input parameter is unused.

==== Post-conditions

The result contains the list of target addresses configured for the server.

==== Rationale

Used for checking the server configuration.

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "string",
  "description": "Unused",
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": "string",
  "description": "Target addresses",
}
```
====

[NOTE]
====
This method does not return errors.
====

=== getCurrentSyncedBlock

Retrieves the block information from which the indexers are synced at, and the tip of the connected node.

In the implementation, it actually queries the UTXO indexer and doesn't return the last indexed chainpoint, but the one before.
The reason is that we want to use this query to find a sync point that is common to all the indexers
that are under the same coordinator.
Unfortunately, while the coordinator ensures that all the indexer move at the same speed,
it can't monitor if the last submitted block was indexed by all the indexers or not.

As a consequence, if the last chainpoint of the utxo indexer can, at most,
be ahead of one block compared to other indexers.
Taking the chainpoint before ensure that we have consistent infomation across all the indexers.

==== Pre-conditions

None as there are no required inputs.

==== Post-conditions

* The result represents the block *right before* the actual synced block my `marconi-sidechain`.

==== Rationale

This endpoint is not called during normal operation of the Sidechain.
It’s triggered when a user calls the Sidechain API to get info about the state of the node.

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "oneOf": [
    { "const": {} },
    { "const": "" },
    { "const": null },
    { "const": undefined },
}
```
====

[NOTE]
====
The param object can be fully omitted for this method.
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "blockNo": {
      "type": "integer",
      "minimum": 0
    },
    "blockTimestamp": {
      "type": "string",
      "minimum": 0,
      "description": "timestamp in seconds"
    },
    "blockHeaderHash": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "slotNo": {
      "type": "integer",
      "minimum": 0
    },
    "epochNo": {
      "type": "integer",
      "minimum": 0
    },
    "nodeTip": {
      "type": "object",
      "properties": {
        "blockNo": {
          "type": "integer",
          "minimum": 0
        },
        "blockHeaderHash": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "slotNo": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "blockNo",
        "blockHeaderHash",
        "slotNo"
      ]
    }
  },
  "required": []
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The param value must be empty (use '{}', 'null', empty string or omit the param object entirely)."
    }
  ]
}
```
====

=== getUtxosFromAddress

Retrieves UTXOs of a given address until a given slot, and optionally after a given slot.

==== Pre-conditions

* The `address` param value must be in the Bech32 format.

* If `marconi-sidechain` was configured to track a specific set of addresses, then the `address` param value should be part of them.

* The `createdAtOrAfterSlotNo` and `unspentBeforeSlotNo` param values must be natural numbers starting at 0.

* The `unspentBeforeSlotNo` param value should be larger than the `createdAtOrAfterSlotNo`.

==== Post-conditions

* The `datumHash` result value should always be available if the `datum` result value is available.

* The `slotNo` result value should be larger than provided `createdAtOrAfterSlotNo` param value.

* The `slotNo` result value should be lower than the provided `unspentBeforeSlotNo` param value.

* The `slotNo` result value should be larger or equal to the `blockNo` result value.

* In the `value` result value, the AssetName key should always be empty if the linked PolicyId is empty.

==== Rationale

The main use case of this endpoint will be to get registration UTXOs.
Since you need to be an SPO to be a valid candidate then we can expect the number of result to be the same order of magnitude as the number of SPO on Cardano, ~500 at the moment on mainnet.

Note that since since anyone can create a UTXO belonging to a validator, there is not an exact 1-1
correspondance between the number of UTXOS and the number of SPOs.
Additionally, a SPO can create several valid registrations (last one wins), to declare a new public key for instance.
They are expected, however, to clean up older registration.

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "address": {
      "type": "string",
      "description": "Show UTxOs belonging to this Shelley address in the Bech32 format."
    },
    "createdAtOrAfterSlotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Filter out UTxO that were created during or before that slot."
    },
    "unspentBeforeSlotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Show only UTxOs that existed at this slot. Said another way, only outputs that were created during or before that slot and remain unspent up to and including that slot will be returned."
    }
  },
  "required": [
    "address"
  ]
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "slotNo": {
        "type": "integer",
        "minimum": 0
      },
      "blockNo": {
        "type": "integer",
        "minimum": 0
      },
      "txIndexInBlock": {
        "type": "integer",
        "minimum": 0
      },
      "datum": {
        "type": "string",
        "description": "JSON encoded datum of the UTXO."
      },
      "datumHash": {
        "type": "string",
        "description": "Hash of the datum"
      },
      "txId": {
        "type": "string"
      },
      "txIx": {
        "type": "integer",
        "minimum": 0
      },
      "spentBy": {
        "type": "object",
        "properties": {
          "slotNo": {
            "type": "integer",
            "minimum": 0
          },
          "txId": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          }
        },
        "required": [
          "slotNo",
          "txId"
        ]
      },
      "txInputs": {
        "type": "array",
        "description": "List of inputs that were used in the transaction that created this UTxO.",
        "items": {
          "type": "object",
          "properties": {
            "txId": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            },
            "txIx": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": [
            "txId",
            "txIx"
          ]
        }
      },
    },
    "value": {
      "type": "object",
      "description": "The key represents the PolicyId of the value. The empty string refers to ADA.",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "description": "The key represents the AssetName of the value linked to a particular PolicyId. If the PolicyId is the empty string, then the AssetName should also be the empty string. Additionaly, if the PolicyId is not the empty string, the AssetName can be empty.",
          "patternProperties": {
            "^.*$": {
              "type": "number"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "required": [
      "blockHeaderHash",
      "blockNo",
      "slotNo",
      "txId",
      "txIx",
      "txIndexInBlock",
      "txInputs",
      "value"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'address' param value must be in the Bech32 format."
    },
    {
      "const": "The 'address' param value must belong to the provided target addresses."
    },
    {
      "const": "The 'createAfterSlotNo' param value must be a natural number."
    },
    {
      "const": "The 'unspentBeforeSlotNo' param value must be a natural number."
    },
    {
      "const": "The 'unspentBeforeSlotNo' param value must be larger than 'createAfterSlotNo'."
    },
  ]
}
```
====


=== getBurnTokenEvents

Retrieves all token burning events given an `AssetId` that have occurred before a given slot, and optionally after a given transaction ID.

==== Pre-conditions

* The `policyId` param value must be a valid minting policy hash.

* The `createdAfterTx` param value must be a valid transaction ID.

* If `marconi-sidechain` was configured to track a specific set of `AssetIds`, then the pair `(policyId, assetName)` param value should be part of them.

* The `createdAfterTx` param value must be an existing transaction ID in the Cardano network that burned a token (`AssetId`).

* The `createdBeforeSlotNo` param value must be natural numbers starting at 0.

* The `createdBeforeSlotNo` param value should be larger than the slot number where the `createdAfterTx` transaction has appeared in the network.

==== Post-conditions

* The `burnAmount` must *always* be a natural number.
  A negative number means that the token was minted.
  However, we don't track mint events, so that should never happen.

* If the `policyId` correspond to a simple script, the response won't contain a
  `redeemer`. Otherwise, the response *always* contain a redeemer.

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "policyId": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "Minting policy hash of the AssetId."
    },
    "assetName": {
      "type": "string",
      "pattern": "^([0-9a-f]{2})+$",
      "description": "Name of the AssetId."
    },
    "createdBeforeSlotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Return the state of the chain at this slot. Effectively it filters out transactions that occured during or after this slot."
    },
    "createdAfterTx": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "Filters out transaction that occurred before this transaction. The specific transaction must be part of the indexed transactions."
    }
  },
  "required": [
    "policyId",
  ]
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "slotNo": {
        "type": "integer",
        "minimum": 0
      },
      "blockNo": {
        "type": "integer",
        "minimum": 0
      },
      "txId": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "redeemer": {
        "type": "string",
        "pattern": "^([0-9a-f]{2})+$"
      },
      "burnAmount": {
        "type": "integer"
        "minimum": 0
      },
      "isStable": {
        "type": "boolean"
      }
    },
    "required": [
      "blockHeaderHash",
      "slotNo",
      "blockNo",
      "txId",
      "burnAmount",
      "redeemer",
      "isStable"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'policyId' param value must be a valid minting policy hash."
    },
    {
      "const": "The 'createdAfterTx' param value must be a valid transaction ID."
    },
    {
      "const": "The 'policyId' and 'assetName' param values must belong to the provided target 'AssetIds'."
    },
    {
      "const": "The 'createdAfterTx' param value must be an existing transaction ID in the Cardano network that burned a token ('AssetId')."
    },
    {
      "const": "The 'createdBeforeSlotNo' param value must be a natural number."
    },
    {
      "const": "The 'createdBeforeSlotNo' param value must be larger than the slot number of the 'createdAfterTx' transaction."
    },
  ]
}
```
====


=== getNonceByEpoch

Retrieves the nonce per epoch.

==== Pre-conditions

* The `epochNo` param value must be a natural number.

==== Post-conditions

* The `nonce` result value must only be returned when the `epochNo` is in an era that has epoch nonces (for example, Byron era doesn't have nonces).

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "integer",
  "minimum": 0,
  "description": "Epoch number"
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "blockHeaderHash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "blockNo": {
      "minimum": 0,
      "type": "integer"
    },
    "epochNo": {
      "minimum": 0,
      "type": "integer"
    },
    "slotNo": {
      "minimum": 0,
      "type": "integer"
    },
    "nonce": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    }
  },
  "required": [
    "blockHeaderHash",
    "blockNo",
    "epochNo",
    "nonce",
    "slotNo"
  ]
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'epochNo' param value must be a natural number."
    }
  ]
}
```
====


=== getActiveStakePoolDelegationByEpoch

Retrieves the active stake pool delegation per epoch.

==== Pre-conditions

* The `epochNo` param value must be a natural number.

==== Post-conditions

* The result value of stake pool delegations must only be returned when the `epochNo` is in an era that has support for stake pools (for example, Byron era doesn't have stake pools).

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "integer",
  "minimum": 0,
  "description": "Epoch number"
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "pattern": "^[0-9a-f]{64}$",
        "type": "string"
      },
      "blockNo": {
        "minimum": 0,
        "type": "integer"
      },
      "slotNo": {
        "minimum": 0,
        "type": "integer"
      },
      "epochNo": {
        "minimum": 0,
        "type": "integer"
      },
      "poolId": {
        "type": "string"
      },
      "lovelace": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "blockHeaderHash",
      "blockNo",
      "slotNo",
      "epochNo",
      "poolId",
      "lovelace"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'epochNo' param value must be a natural number."
    }
  ]
}
```
====
