= JSON-RPC API
:toc: left
:toclevels: 2

This document describes the JSON-RPC HTTP API that end-users will interact with in order to query the data indexed by `marconi-sidechain`.

== HTTP endpoint

In this application, there is a single HTTP endpoint/route: `POST /json-rpc`.
This endpoint will listen and respond to well-formed link:https://www.jsonrpc.org/specification[JSON-RPC version 2] requests and responses.
Each of the following subsections reflect the JSON-RPC methods that can be used in the JSON-RPC request.

== JSON-RPC HTTP endpoint request and response format

As defined by the JSON-RPC specification, `marconi-sidechain` can process the following JSON-RPC HTTP request and response format.

[NOTE]
====
All JSON formats in this document are described using link:https://json-schema.org[JSON-Schema].
====

.JSON-RPC HTTP request body
[%collapsible]
====
```JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "jsonrpc": {
      "type": "string"
    },
    "method": {
      "type": "string"
    },
    "params": {
      "type": {}
    },
    "id": {
      "type": "integer"
    }
  },
  "required": [
    "jsonrpc",
    "method",
    "params",
    "id"
  ]
}
```
====

.JSON-RPC HTTP response body
[%collapsible]
====
```JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "jsonrpc": {
          "type": "string"
        },
        "result": {}
      },
      "required": [
        "id",
        "jsonrpc",
        "result"
      ]
    },
    {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "jsonrpc": {
          "type": "string"
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "number"
            },
            "message": {
              "type": "string"
            },
            "data": {}
          },
          "required": [
            "code",
            "message"
          ]
        }
      },
      "required": [
        "id",
        "jsonrpc",
        "error"
      ]
    }
  ]
}
```
====

== Error object

In case of runtime errors, the JSON-RPC server will respond with any of the predefined errors code defined here: https://www.jsonrpc.org/specification#error_object.
However, each supported JSON-RPC methods described below will respond with a custom `data` field which provides additional/detailed information about the error.

== Supported JSON-RPC methods

=== getCurrentSyncedBlock

Retrieves the block information from which the indexers are synced at.

It queries the UTXO indexer and doesn't return the last indexed chainpoint, but the one before.
The reason is that we want to use this query to find a sync point that is common to all the indexers
that are under the same coordinator.
Unfortunately, while the coordinator ensures that all the indexer move at the same speed,
it can't monitor if the last submitted block was indexed by all the indexers or not.

As a consequence, if the last chainpoint of the utxo indexer can, at most,
be ahead of one block compared to other indexers.
Taking the chainpoint before ensure that we have consistent infomation across all the indexers.

==== Pre-conditions

None as there are no required inputs.

==== Post-conditions

* The result represents the block *right before* the actual synced block my `marconi-sidechain`.

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "oneOf": [
    { "const": {} },
    { "const": "" },
    { "const": null },
    { "const": undefined },
}
```
====

[NOTE]
====
The param object can be fully omitted for this method.
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "blockNo": {
      "type": "integer",
      "minimum": 0
    },
    "blockTimestamp": {
      "type": "string",
      "minimum": 0,
      "description": "timestamp in seconds"
    },
    "blockHeaderHash": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "slotNo": {
      "type": "integer",
      "minimum": 0
    },
    "epochNo": {
      "type": "integer",
      "minimum": 0
    }
  },
  "required": []
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The param value must be empty (use '{}', 'null', empty string or omit the param object entirely)."
    }
  ]
}
```
====

=== getUtxosFromAddress

Retrieves UTXOs of a given address until a given slot, and optionally after a given slot.

==== Pre-conditions

* The `address` param value must be in the Bech32 format.

* If `marconi-sidechain` was configured to track a specific set of addresses, then the `address` param value should be part of them.

* The `createdAfterSlotNo` and `unspentBeforeSlotNo` param values must be natural numbers starting at 0.

* The `unspentBeforeSlotNo` param value should be larger than the `createdAfterSlotNo`.

* The `createdAfterSlotNo` param value must be lower or equal to the current indexed `SlotNo` (returned by the `getCurrentSyncedBlock` endpoint).

==== Post-conditions

* The `datumHash` result value should always be available if the `datum` result value is available.

* The `slotNo` result value should be larger than provided `createdAfterSlotNo` param value.

* The `slotNo` result value should be lower than the provided `unspentBeforeSlotNo` param value.

* The `slotNo` result value should be larger or equal to the `blockNo` result value.

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "address": {
      "type": "string",
      "description": "Show UTxOs belonging to this Shelley address in the Bech32 format."
    },
    "createdAfterSlotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Filter out UTxO that were created during or before that slot."
    },
    "unspentBeforeSlotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Show only UTxOs that existed at this slot. Said another way, only outputs that were created during or before that slot and were unspent during that slot will be returned."
    }
  },
  "required": [
    "address"
  ]
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "slotNo": {
        "type": "integer",
        "minimum": 0
      },
      "blockNo": {
        "type": "integer",
        "minimum": 0
      },
      "txIndexInBlock": {
        "type": "integer",
        "minimum": 0
      },
      "datum": {
        "type": "string",
        "description": "JSON encoded datum of the UTXO."
      },
      "datumHash": {
        "type": "string",
        "description": "Hash of the datum"
      },
      "txId": {
        "type": "string"
      },
      "txIx": {
        "type": "integer",
        "minimum": 0
      },
      "spentBy": {
        "type": "object",
        "properties": {
          "slotNo": {
            "type": "integer",
            "minimum": 0
          },
          "txId": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          }
        },
        "required": [
          "slotNo",
          "txId"
        ]
      },
      "txInputs": {
        "type": "array",
        "description": "List of inputs that were used in the transaction that created this UTxO.",
        "items": {
          "type": "object",
          "properties": {
            "txId": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            },
            "txIx": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": [
            "txId",
            "txIx"
          ]
        }
      },
    },
    "required": [
      "blockHeaderHash",
      "blockNo",
      "slotNo",
      "txId",
      "txIx",
      "txIndexInBlock",
      "txInputs"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'address' param value must be in the Bech32 format."
    },
    {
      "const": "The 'address' param value must belong to the provided target addresses."
    },
    {
      "const": "The 'createAfterSlotNo' param value must be a natural number."
    },
    {
      "const": "The 'unspentBeforeSlotNo' param value must be a natural number."
    },
    {
      "const": "The 'unspentBeforeSlotNo' param value must be larger than 'createAfterSlotNo'."
    },
    {
      "const": "The 'createAfterSlotNo' param value must be lower than the latest indexed SlotNo."
    }
  ]
}
```
====


=== getBurnTokensEvents

Retrieves all token burning events given an `AssetId` that have occurred before a given slot, and optionally after a given transaction ID.

==== Pre-conditions

* The `policyId` param value must be a valid minting policy hash.

* The `afterTx` param value must be a valid transaction ID.

* If `marconi-sidechain` was configured to track a specific set of `AssetIds`, then the pair `(policyId, assetName)` param value should be part of them.

* The 'afterTx' param value must be an existing transaction ID in the Cardano network that burned a token ('AssetId').

* The `slotNo` param value must be natural numbers starting at 0.

* The `slotNo` param value should be larger than the slot number where the `afterTx` transaction has appeared in the network.

==== Post-conditions

* The `burnAmount` must *always* be a natural number.
  A negative number means that the token was minted.
  However, we don't track mint events, so that should never happen.

* If the `policyId` correspond to a simple script, the response won't contain a
  `redeemer`. Otherwise, the response *always* contain a redeemer.

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "policyId": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "Minting policy hash of the AssetId."
    },
    "assetName": {
      "type": "string",
      "pattern": "^([0-9a-f]{2})+$",
      "description": "Name of the AssetId."
    },
    "slotNo": {
      "type": "integer",
      "minimum": 0,
      "description": "Return the state of the chain at this slot. Effectively it filters out transactions that occured during or after this slot."
    },
    "afterTx": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "Filters out transaction that occurred before this transaction. The specific transaction must be part of the indexed transactions."
    }
  },
  "required": [
    "policyId",
  ]
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "slotNo": {
        "type": "integer",
        "minimum": 0
      },
      "blockNo": {
        "type": "integer",
        "minimum": 0
      },
      "txId": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "redeemer": {
        "type": "string",
        "pattern": "^([0-9a-f]{2})+$"
      },
      "burnAmount": {
        "type": "integer"
        "minimum": 0
      }
    },
    "required": [
      "blockHeaderHash",
      "slotNo",
      "blockNo",
      "txId",
      "burnAmount"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'policyId' param value must be a valid minting policy hash."
    },
    {
      "const": "The 'afterTx' param value must be a valid transaction ID."
    },
    {
      "const": "The 'policyId' and 'assetName' param values must belong to the provided target 'AssetIds'."
    },
    {
      "const": "The 'afterTx' param value must be an existing transaction ID in the Cardano network that burned a token ('AssetId')."
    },
    {
      "const": "The 'slotNo' param value must be a natural number."
    },
    {
      "const": "The 'slotNo' param value must be larger than the slot number of the 'afterTx' transaction."
    },
  ]
}
```
====


=== getNonceByEpoch

Retrieves the nonce per epoch.

==== Pre-conditions

* The `epochNo` param value must be a natural number.

* The `epochNo` param value must be in an era that has epoch nonces (for example, Byron era doesn't have nonces).

==== Post-conditions

* The `nonce` result value must be in an era that has epoch nonces (for example, Byron era doesn't have nonces).

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "integer",
  "minimum": 0,
  "description": "Epoch number"
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "object",
  "properties": {
    "blockHeaderHash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "blockNo": {
      "minimum": 0,
      "type": "integer"
    },
    "epochNo": {
      "minimum": 0,
      "type": "integer"
    },
    "slotNo": {
      "minimum": 0,
      "type": "integer"
    },
    "nonce": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    }
  },
  "required": [
    "blockHeaderHash",
    "blockNo",
    "epochNo",
    "nonce",
    "slotNo"
  ]
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'epochNo' param value must be a natural number."
    },
    {
      "const": "The 'epochNo' param value must belong in an era that has nonces (Byron era doesn't have nonces)."
    }
  ]
}
```
====


=== getActiveStakePoolDelegationByEpoch

Retrieves the active stake pool delegation per epoch.

==== Pre-conditions

* The `epochNo` param value must be a natural number.

==== Post-conditions

TBD

==== Rationale

TBD

==== JSON Schema

.JSON-RPC param object
[%collapsible]
====
```JSON
{
  "type": "integer",
  "minimum": 0,
  "description": "Epoch number"
}
```
====

.JSON-RPC result object
[%collapsible]
====
```JSON
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blockHeaderHash": {
        "pattern": "^[0-9a-f]{64}$",
        "type": "string"
      },
      "blockNo": {
        "minimum": 0,
        "type": "integer"
      },
      "slotNo": {
        "minimum": 0,
        "type": "integer"
      },
      "epochNo": {
        "minimum": 0,
        "type": "integer"
      },
      "poolId": {
        "type": "string"
      },
      "lovelace": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "blockHeaderHash",
      "blockNo",
      "slotNo",
      "epochNo",
      "poolId",
      "lovelace"
    ]
  }
}
```
====

.JSON-RPC error data object
[%collapsible]
====
```JSON
{
  "oneOf": [
    {
      "const": "The 'epochNo' param value must be a natural number."
    }
  ]
}
```
====
