---
resolver: lts-11.8
packages:
  - '.'
extra-deps:
  - containers-0.5.11.0
flags:
  language-plutus-core:
    development: true
  comonad:
    test-doctests: false
  semigroupoids:
    doctests: false
  lens:
    test-doctests: false
extra-package-dbs: []
