= ADR 1: Stake pool delegation distribution computation

Date: 2023-05-01

== Author(s)

@koslambrou <konstantinos.lambrou@iohk.io>

== Status

Draft

== Context

The Sidechain application needs to know the Cardano blockchain active stake pool delegation distribution (SDD) for epoch `n`.
It will use that information to register the committee that will be used to validate sidechain blocks in epoch `n+1`.

Here's the list of assumptions:

* `marconi-sidechain` will be run by a Stake Pool Operator (SPO)
* `marconi-sidechain` will communicate with a relay node (not the block producing node)

The main architectural goal we are trying to achieve is to reduce as much as possible the hardware resource usage of a SPO.
Therefore, indexing the SDD per epoch should be as resource efficient as possible.

== Decision(s)

TBD

== Possible solutions

We will describe all the potential and discussed solutions to index the SDD of each epoch in the following sections.

As a summary, we provide the following caracteristics table and indicate how each solution responds to them.
This assessment is measured in regards to two components: Cardano Node and Marconi.



.Comparison of solutions using a list of caracteristics
[cols="1,1,1,1,1"]
|===
|Caracteristics | Marconi LedgerState computation | Read LedgerEvents from node | SDD using N2C | Marconi as a node

|Number of LedgerState computations | 2 | 1 | 1 | 1
|Initial node resync required | No | Yes | Yes | Yes
|Required node resync after Marconi logic change | No | No | Yes | Yes
|Change to cardano-node | No | Yes | No | No
|===

.Description of the caracteristics
[cols="1,1"]
|===
|Caracteristics | Description

|Number of LedgerState computations
|As it suggest, corresponds to total number of independent computations of the LedgerState.

|Initial node resync
|Yes if a resync of the relay node is required. No otherwise.

|Node resync after schema change
|Yes if a resync of the relay node is required after any changes to the indexing logic of Marconi.

|Change to cardano-node
|Yes if the solution requires a change to the cardano-node codebase.

|===

For more details, read the sections below.

=== 1. Compute SDD by computing the `LedgerState`

This is the approach that `cardano-db-sync` currently uses to compute the SDD for each epoch.

A container diagram of this solution would look like:

image::http://www.plantuml.com/plantuml/png/jL0_Q-Cm5D_zANIU4ZZ7SDnqKovkbz8w9g5pKAJNM4H_XFJKr9H-zqfAunfAe4ityNx_jVH87GObYrz2Cnaua1xH-dzrxUXfSH3OXttmu9ZH21eNpAZQIggJflB8fTZNpT-gIwV7X_jQKO_WucdNH0KL6jp2_eZ_3LXf1fL4EQ1e3OUPj-OtARVTcl0HB-VajIZ6FZEd8sK3aWuaQShv1DlR1AwaOKVIESC34_fmeQr4L6NvcHRBgg05emYUdEAMCXxRFosnpg1XHaRDn5lHD5D4piUhye83woCQYSbwPEIAJu2iZywPKVb1CmBFeD6VOvehCQDf-eZBc_otzXmonJyRCIfbzhtRhjjgqpNZt0dTNHdzjKtnLXJRmIEetUqBpY0h6-eurOPem9Dnnp4Xe-wx7xe4pOEIxm00[]

Here is a general outline of the computation of the `LedgerState`:

. At the start of `marconi-sidechain`, initialize the `LedgerState` (or `NewEpochState`) given the node genesis file
. Get block from the chain sync protocol
. Update the `LedgerState` given the block
. Compute the SDD from the new LedgerState and store in the database
. Repeat from step 2

While this approach is the "easiest" to implement, it suffers from major drawbacks such as:

* adding an additional 10-16GB of RAM in `marconi-sidechain` just from computing the `LedgerState`
* slowing down indexing.
  Computation of the `LedgerState` is _the_ bottleneck in `marconi-sidechain`
* duplicating the computation of the LedgerState which is already computed by the Cardano node which `marconi-sidechain` is connected to

These drawbacks are significant enough that alternative solutions need to be explored.

=== 2. Add an option to cardano-node for storing LedgerEvents

As we said, `cardano-node` already computes and keeps an up-to-date `LedgerState` while syncing.
As `marconi-sidechain` is connecting to a Cardano node, it should be possible to get the `LedgerState` directly from the node instead of computing it in `marconi-sidechain`.
This would result in a significant improvement in memory usage.

However, there is an important issue with this approach.
Other than the state query client of the node-to-client protocol, which only gives you the latest `LedgerState`, there is no support for querying historical `LedgerState` values (i.e. for any block or epoch in the chain).

[NOTE]
====
We discuss an alternative solution to the problem using the state query client of the node-to-client protocol in the section below.
====

Therefore, this solution would require either

* adding a CLI option for the `cardano-node` executable to optionally store on disk the `LedgerState` (or more specifically the `LedgerEvent`) for each epoch (or slot, but with the consequence of reducing syncing speed)

or

* providing a forked node which stores this information (if that change will not be accepted in the `cardano-node` repository)

In either of those case, the SPO would need to replace one of its relay nodes with a node which saves on disk the `LedgerEvent` for each epoch.
Then, any chain-indexer (like `marconi-sidechain`) will read these `LedgerEvent` and index the required information (the SDD in our scenario).

[NOTE]
====
At this stage, it is important to note why we suggest to store `LedgerEvent` and not the full `LedgerState`.
A `LedgerEvent` is derived from the `LedgerState` and describes changes to the `LedgerState` after each block is applied.
Thus, it is a smaller data structure when compared to `LedgerState`.
See https://github.com/input-output-hk/cardano-ledger/blob/master/docs/LedgerEvents.md for more information.
====

A container diagram of this solution would look like:

image::http://www.plantuml.com/plantuml/png/jL7DRfmm4Bxp52ud8fL5gdhgAGsRIvKIb5NFaR67nOf_B7ieHLNVlRPtbmLfLVMI0vAPxsU-cRdtI1sEIcOVX6Pov406HEk_L9MZq-ueS1YxqODZHYDet36ZAYkfZfhI8vUYg-hFPHjBFxu_LOfw11TAhtLGKA71xUox-E_1IZEhA4eDiiPmABmr7qb-Q9y9N_3yZlpEiYLFuNIWl82aCucQ_6w5TJQ23zAmDz8wmqSczF52Un11bUGdMWYhHYqOHV1a2hFaeTXyQeXr1WqpCcYktlkkqC7d2VWHtEDFqBZl0d_rxmF_qk4MTN82OUDPA1fN9m9uVfLUS613GCzc2oEDtGEo8QHDZDBFcX58hK_HwoNwLdqxZmFAjt6Mvl48bpVvQcsqZrzFUpf1VtPVqQ-3C2fbYlFjyDoKBsszR7v5T__O_sQ8Frbsc3s2UdtyXGKaNKqTfzeG3JWPzxRu9zJzxsNlGVDHoRy0[]

The benefits:

* removal of the additional 10-16GB of memory needed to compute the `LedgerState` in `marconi-sidechain`
* enables any chain-indexers (`cardano-db-sync`, `Kupo`, etc) to read the stored `LedgerEvent` in order to index various information like SDD and rewards without using a large amount of memory

The drawbacks:

* requires a change to `cardano-node` in order to store those LedgerEvents. This implies lots of discussions with the `cardano-node` team to accept such a change.
* needs the SPO to resync the relay node from scratch in order to save the `LedgerEvent` on disk. However, such a resync will only be required once, even after an upgrade on `marconi-sidechain`.
* need to maintain a separate fork of the `cardano-node` in the event of the node team not agreeing to merge those changes

=== 3. Index SDD from the state query client of the node-to-client protocol

This alternative solution takes advantage of the only way currently to get the SDD from a `cardano-node` by using the state query client of the node-to-client protocol.
However, the query will only return the latest SDD given the slot from which the Cardano node is synced to.
In order to take advantage of this functionality, we would need to change the deployment method of `marconi-sidechain` to something as follows:

. The SPO needs to stop the relay node and delete the `cardano-node` database
. Start `marconi-sidechain` which will wait for the node to start
. Start the relay node
. Once Marconi has noticed that the node has started syncing, it will start querying the local query state for the SDD for each new epoch and index it in the database.

Is is important to note that any changes in the indexers of `marconi-sidechain` would require a complete resync of `marconi-sidechain`.
As a direct consequence of this solution, the user would be required to delete the node database in order to reindex everything.

The container diagram is the same as the link:#compute-sdd-by-tracking-the-ledgerstate[Compute SDD by tracking the LedgerState] solution.

The benefits:

* no change to `cardano-node` are required
* uses the existing infrastructure to get the required information

The drawbacks:

* needs the SPO to resync the relay node from scratch
* any change in the indexing logic of `marconi-sidechain` would require resyncing from scratch the local node (thus deleting the node database)
* overhead of needing to continuously poll the relay node to identify when a new epoch occurs
* race condition between node and `marconi-sidechain`. If a node syncs too fast and `marconi-sidechain` is stalled because of some heavy processing, we might miss an epoch (unlikely, but possible).

=== 4. Transform `marconi-sidechain` to a Cardano relay node

`marconi-sidechain` could be changed to become _a_ Cardano node and replace the SPO's relay node.
Then, it would have the same functionality as a relay (using node-to-node protocol), but also index
the necessary for the Sidechain team.

Ultimately, the `marconi-sidechain` process would run two computations in parallel: the N2N protocol
and the indexers.
Then, we would need to find a way to get the `LedgerState` that's computed by the node's consensus
layer and wire it to the indexers.

A container diagram of this solution would look like:

image::http://www.plantuml.com/plantuml/png/jO_1JW8n48RlVOgw9qY4JOmdJyZgnSYoWNWcfPr0GzjfsccG6D_TLW8BYIPUl4sdt_pppIII29IiOJVQIPCKy2sHZmzr7SH-lD6qJUiK8KXq18x64ctjZN1bPXH96Rskc_jHLrflizVQYaWGSclLe2EX7OIn_vVy9_063xOCVIzWBIeOH8-tl5fsSwxE_zMGVp1szXcilSlCrA3SyIwWIbAx3I_ZrV2Iiw9ewSpEZXLVW1674pdL-Tb3nrI9rYQdfI28V9_FgtAplMkv3qWeqLolY5g1tEQwI9zg_kXznahwnNzl8uKniUI-BEVjQD4rHvaVyT-LcYkbJyQMXqXWLy_lD81GX1eHb7387T0Um-wy1KAV_yUJ9-1KikOB[]

The benefits:

* no change to `cardano-node` are required
* only one computation of `LedgerState` is required

The drawbacks:

* uncertainty of capability to use `cardano-node` as a library
* any change in the indexing logic of `marconi-sidechain` would require resyncing from scratch the local node (thus deleting the node database)
* needs the SPO to resync the relay node from scratch

=== 5. Use Mithril SDD snapshots

An approach that has been proposed would be to use the SDD snapshots provided by Mithril.
Then, `marconi-sidechain` would simply fetch those snapshots and index them in its database.

However, it is unclear at what points in time the snapshots will available.
We expect the Sidechain team to need SDD for epochs close to the tip of the Cardano chain.
Therefore, our intuition is that Mithril could be used to _bootstrap_ `marconi-sidechain` for faster syncing, but we would still need to implement one of the previous solutions to index the SDD that occur on epochs after the latest Mithril snapshot.

== Implications

== Notes

=== 2023/05/03

Discussing with @abailly-iohk, seems like the "ideal" solution would be to transform `marconi-sidechain` to a Cardano node using the node-to-node protocol and replace the SPO's relay node.
However, we require product input from the Sidechain team given the changes that an SPO would have to do.
