name: "Build and Deploy to Github Pages"
on:
  push:
    branches:
      - main
      - will/PLT-5743/deploy-haddock-github-page
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-haddock-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Build haddock site
        run: |
          ghcup nuke
          nix develop --command bash -c '
              cabal update
              cabal haddock marconi-core
              cabal haddock marconi-chain-index
              cabal haddock marconi-core-json-rpc
            '
          mkdir dist
          mkdir dist/marconi-core
          mkdir dist/marconi-chain-index
          mkdir dist/marconi-core-json-rpc
          cp -RL ./dist-newstyle/build/x86_64-linux/ghc-9.2.8/marconi-core-1.2.0.0/doc/html/marconi-core/* ./dist/marconi-core
          cp -RL ./dist-newstyle/build/x86_64-linux/ghc-9.2.8/marconi-chain-index-1.2.0.0/doc/html/marconi-chain-index/* ./dist/marconi-chain-index
          cp -RL ./dist-newstyle/build/x86_64-linux/ghc-9.2.8/marconi-core-json-rpc-1.2.0.0/doc/html/marconi-core-json-rpc/* ./dist/marconi-core-json-rpc
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}